### ISSUE TITLE
Warning message causes rs_replace_table() function not to upload data

### ISSUE THREAD

**Issue by Emelieh21** [sicarul/redshiftTools#10]
First of all: thanks for the very useful package. I am a frequent user of the rs_replace_table function. However, today I noticed the upload to Redshift from S3 does not continue when a warning occurs. 

I got this warning:

`<simpleWarning in result_fetch(res@ptr, n = n): Don't need to call dbFetch() for statements, only for queries>`

And after that **the upload to Redshift was skipped** and the tables were deleted again from the S3 bucket. 

After removing the line `warning = function(w) { print(w) }` from the rs_replace_table function in my R session (see replace.R line 97-99), it worked fine again. Not sure if you intended the upload to stop when a warning occurs, but I just wanted to inform you about this issue.

**Comment by sicarul** [comment]
You are right, the upload shouldn't stop for a warning, my mistake. Can you send a Pull Request with the change?

Thanks!

**Comment by sicarul** [comment]
Thanks for the PR! Fixed by #12 
Closing this issue
