### ISSUE TITLE
receiving "ERROR:  Query cancelled on user's request\n" in version 0.3.900

### ISSUE THREAD

**Issue by tharpole-chwy** [sicarul/redshiftTools#11]
I am trying to use the rs_upsert_table command after upgrading to version 0.3.900 and receive the error "ERROR:  Query cancelled on user's request\n"

However, the exact same commands in version 0.1.1 do not produce this error. Any idea what has changed that has caused this? Should I simply downgrade my version? Any help installing an older version?

For reference, my commands look like:
dbSendQuery(con2,"create table newTABLE(
            x VARCHAR(100),
            y VARCHAR(100),
            z VARCHAR(100),
            i integer,
            j integer);")
rs_upsert_table(dF,dbcon=con2,table_name="newTABLE",bucket="myBucket")

**Comment by sicarul** [comment]
@harpole2 i've found this issue with older RPostgres versions, can you try upgrading to the latest CRAN version?

```
install.packages('RPostgres')
```
If this doesn't work, please tell me the version you have installed of RPostgres

Thanks

**Comment by tharpole-chwy** [comment]
Update: It seems like the error below only occurs when split_files is not defined. Maybe because the number is so small? When I use split_files=1, no error occurs.

I updated to version 1.0.4 of RPostgres. Now, the table is being created, but not all the rows are moving over. Example output looks like this:

[1] "The provided data.frame has 2268 rows"
[1] "Getting number of slices from Redshift"
[1] "1.97626258336499e-323 slices detected, will split into 3.95252516672997e-323 files"
[1] "Uploading qvyodrikjxumtzfh.0001"
[1] "Uploading qvyodrikjxumtzfh.0000"
[1] "Copying data from S3 into Redshift"
INFO:  Load into table 'znumheoylfgjtbwk' completed, 1134 record(s) loaded successfully.
[1] "Deleting target table for replacement"
[1] "Insert new rows"
[1] "Drop staging table"
[1] "Committing changes"
[1] "Deleting temporary files from S3 bucket"
[1] "Deleting qvyodrikjxumtzfh.0001"
[1] "Deleting qvyodrikjxumtzfh.0000"
[1] TRUE

Any idea why only half the rows get transfered?

**Comment by sicarul** [comment]
@harpole2 I think i identified the problem with yesterday's commit, can you reinstall redshiftTools and retry the same? Please notify me, thanks!

**Comment by sicarul** [comment]
Closing on inactivity, reopen if this keeps happening
