### ISSUE TITLE
Not working for tables with an identity column

### ISSUE THREAD

**Issue by frantisekjodel** [sicarul/redshiftTools#14]
(edited after spending more time working out the issue)

I have a table which has an incremental identity column.

I run:

`rs_replace_table(df = table, dbcon = con, table_name = 'table', bucket = "bucket")`

And get the following error after successful upload to S3

```
[1] "Copying data from S3 into Redshift"
[1] "Failed to fetch row: ERROR:  Load into table 'ngphviyuofradklt' failed.  Check 'stl_load_errors' system table for details.\n"
```

The error happens because the temporary table which is created with `like` doesn't take over the property of the id column and it just becomes an ordinary `BIGINT` column. `COPY` fails naturally because there is one column missing in the data frame.

I solved it for my purpose by just directly COPYing into the original table, but it isn't the ideal solution.

**Comment by sicarul** [comment]
I've never used that kind of auto-incrementing fields, is that a usual thing to use in a DataWarehouse?

Here i've used the best practices recommended by Amazon Redshift, if you figure out a correct way to copy the table for tables with autoincrementing ids i can either implement it when i have time, or review your PR if you send it

Thanks for reporting!
Have a nice day

**Comment by frantisekjodel** [comment]
It is a good practice from other SQL databases because of performance, afaik it isn't important in Redshift because of its architecture. However, it can also be there for a purpose, such as identifying newer records, exporting etc. Or simply a column which is already in place in a table which we want to load data into.

I will have a look at a solution from my private GitHub account, and write it here or create a PR.

Thanks for creating this very helpful package, and all the best!

**Comment by sicarul** [comment]
I'll close this issue for now, let me know if you have any proposals and we can reopen
