### ISSUE TITLE
COPY Parameters

### ISSUE THREAD

**Issue by bajacks1** [sicarul/redshiftTools#15]
Hello! Awesome package! Is there a way to pass parameters for the COPY statement (column mapping, data format parameters, data conversion parameters, data load operations)? I'm getting error messages that would be easily remedied with the parameter timeformat = 'auto', but I don't see a way to pass that along. Sorry if this is an inappropriate place to post this question; I am new to GitHub! And thanks in advance for your help!

**Comment by sicarul** [comment]
Hey @bajacks1 do you want to propose this as a Pull request?

**Comment by sicarul** [comment]
@bajacks1 I've added option additional_parameters to support this requirement
https://github.com/sicarul/redshiftTools/commit/3d90556f1fbad9c9b46a2041ab296a705e2a9595

Closing the issue!
