### ISSUE TITLE
specifying s3 keys overwrites env but doesn't reset when done 

### ISSUE THREAD

**Issue by mike-weinberg** [sicarul/redshiftTools#16]
https://github.com/sicarul/redshiftTools/blob/98283805370036974315b3175b8cb5901e7e27f1/R/upsert.R#L71

I may have misunderstood, but it looks like if I specify keys in this function it will implicitly modify my environment for the duration of my R session. That was surprising to me. Is this a deliberate behavior?

**Comment by sicarul** [comment]
You are right, this was an issue. Fixed!
