### ISSUE TITLE
RPostgres supports interactions now

### ISSUE THREAD

**Issue by tomsing1** [sicarul/redshiftTools#17]
Thanks a lot for making this package available!

I noticed that the README mentions that the `RPostgres` package doesn't support transactions for Redshift. Is that still the case after [this issue has been fixed](https://github.com/r-dbi/RPostgres/issues/150) ?

**Comment by sicarul** [comment]
Yes, it works now! I'll update it soon. I've explained all of the features/gotchas of each library connecting to Redshift in this blogpost https://auth0.com/blog/a-comprehensive-guide-for-connecting-with-r-to-redshift/

**Comment by tomsing1** [comment]
Great - thanks for pointing out your blog post!
