### ISSUE TITLE
Issue installing aws.ec2metadata

### ISSUE THREAD

**Issue by RSIGitHubAdmin** [sicarul/redshiftTools#18]
Hi,
The package is not working for me, so I installed the package again, please take a look at the errors and warnings.

> install.packages("aws.ec2metadata", repos = c(cloudyr = "http://cloudyr.github.io/drat", getOption("repos"))) I get the following output:

Installing package into ‘C:/Users/muguet.RSINT/Documents/R/win-library/3.5’
**(as ‘lib’ is unspecified)**
Warning in install.packages :
  cannot open URL 'http://cloudyr.github.io/drat/bin/windows/contrib/3.5/PACKAGES.rds': HTTP status was '404 Not Found'
Warning in install.packages :
  cannot open URL 'http://cloudyr.github.io/drat/bin/windows/contrib/3.5/PACKAGES.gz': HTTP status was '404 Not Found'
Warning in install.packages :
  cannot open URL 'http://cloudyr.github.io/drat/bin/windows/contrib/3.5/PACKAGES': HTTP status was '404 Not Found'
Warning in install.packages :
  unable to access index for repository http://cloudyr.github.io/drat/bin/windows/contrib/3.5:
  cannot open URL 'http://cloudyr.github.io/drat/bin/windows/contrib/3.5/PACKAGES'

  There is a binary version available but the source version is later:
                binary source needs_compilation
aws.ec2metadata  0.1.4  0.1.5             FALSE

installing the source package ‘aws.ec2metadata’

trying URL 'http://cloudyr.github.io/drat/src/contrib/aws.ec2metadata_0.1.5.tar.gz'
Content type 'application/gzip' length 4445 bytes
downloaded 4445 bytes

* installing *source* package 'aws.ec2metadata' ...
** R
** inst
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
  converting help for package 'aws.ec2metadata'
    finding HTML links ... done
    ec2metadata                             html  
** building package indices
** testing if installed package can be loaded
*** arch - i386
*** arch - x64
* DONE (aws.ec2metadata)
In R CMD INSTALL

Thank you

**Comment by sicarul** [comment]
Hey @RSIGitHubAdmin ! I'm seeing in that message that the package installed correctly, are the next steps failing?

It's also not something i can fix, i didn't author that package, it's just a dependency for aws.s3, which is not installed automatically so i added it to instructions.

**Comment by sicarul** [comment]
I'll close this issue for now, let me know if we need to reopen
