### ISSUE TITLE
Function hangs in 3.5.1?

### ISSUE THREAD

**Issue by Horizon-cmchugh** [sicarul/redshiftTools#19]
Hi there, fantastic package, I use this on the regular. Just recently update to R 3.5.1, however, and calling to the function rs_upsert_table seems to hang. It detects the number of splits, but never begins uploading to S3. I've tried the same process on a 3.4.2 installation and it works as normal.

Wondering if you're experiencing this as well or have tried.

Appreciate it!

**Comment by sicarul** [comment]
Not only did i not update @Horizon-cmchugh, i didn't even realize we had 3.5.x yet haha

I can check when i have some time, but if you have some time available, can you try uploading some file with aws.s3 manually? If it's not working, it's not an issue with redshiftTools but the aws.s3 package which we depend on, and it should be reported to that package instead.

Thanks a lot for the report!

**Comment by Horizon-cmchugh** [comment]
Haha, I jumped the gun! I'll try to dig into it some time to see specifically what is causing it to hang and check aws.s3 directly, but will revert back to 3.4.2 in the meantime for loads using your package.

Thanks again for the awesome tool!

**Comment by sicarul** [comment]
Ok, thanks, let me know if we need to change anything, any help to make it work is appreciated too!
