### ISSUE TITLE
S3 bucket name with period causes a curl error in the rs_replace_table function

### ISSUE THREAD

**Issue by samgilbert1983** [sicarul/redshiftTools#2]
It seems the rs_replace_table() function errors when there is a period in the s3 bucket name, if this is the case is there a workaround?

Error message below:

```
Error in curl::curl_fetch_memory(url, handle = handle) : 
  SSL peer certificate or SSH remote key was not OK
```

**Comment by sicarul** [comment]
@samgilbert1983 sorry i just now saw this. It seems this is a problem with upstream library aws.s3:
https://github.com/cloudyr/aws.s3/issues/23

I will check if i can merge a fix during the week, thanks for reporting!

**Comment by sicarul** [comment]
@samgilbert1983 i don't have any buckets with points to test with, i followed the workaround in aws.s3's issue. Can you test if the latest version works for you? Thanks :)

**Comment by sicarul** [comment]
I'll assume it's fixed, let me know otherwise.
