### ISSUE TITLE
Multibyte characters create STL load errors

### ISSUE THREAD

**Issue by mdh1984** [sicarul/redshiftTools#20]
First just wanted to say thanks for creating such a great package. It's been incredibly valuable for me in my work.

The issue I've recently run into has to do with having multibyte characters in my dataset. I work at a digital marketing agency, and occasionally will have trademark symbols and other unicode characters in my datasets. R will interpret this as a single character, but AWS redshift decodes it into multiple characters.

The result is that the **calculateCharSize** function leads to an incorrect table definition (as interpreted by the database) and I get an STL load error as a result.

I've been able to get around this issue by creating a dummy row of data with a longer string, but it may be helpful to modify the **calculateCharSize** function so that it rounds up and sets the character size to the next level. I realize some efficiency might be lost in this approach, but it may be worth it so that others can avoid this same problem.

**Comment by sicarul** [comment]
Can you provide a minimal reproducible example for this problem? That would make it easier to debug

Thanks!

**Comment by mdh1984** [comment]
Yeah definitely! I've attached a .xlsx with one of the rows that was giving me issues (hopefully the encoding of the .xlsx doesn't alter any of the values). In the table you'll also see the nchar() of each string as seen in R. After you pull this into R and try to write it to your database, you'll hopefully see the same STL LOAD ERROR. It looks like the â is being changed to a bunch of dots "...." when writing to the database, so the number of characters for that field is greater than what's being defined by the calculateCharSize function.

Anyway, thanks for looking into it! Let me know if you have any trouble or need any more data.

Cheers!
[multibyte_characters.xlsx](https://github.com/sicarul/redshiftTools/files/2258991/multibyte_characters.xlsx)

**Comment by sicarul** [comment]
Hey @mdh1984 sorry for the late reply, but i have tested this and confirmed that it's already rounding to the next size:
```r
library(tidyverse)
test = tribble(
~ad_title,
"Enjoy Spark Business Checkingâ„ ",
"Meet Spark Business Checkingâ„ "
)

cat(rs_create_statement(test))
```
> CREATE TABLE test (
ad_title VARCHAR(64) encode zstd
);

Are you sure this is causing the issue?

**Comment by mdh1984** [comment]
That's really strange, because I tested and the statement returned VARCHAR(32) for ad_title, so I think something in the encoding must be getting missed across the writing to .csv and copying/pasting. In any case, ever since my hacky fix it hasn't been giving me any issues, and this seems like such a niche problem I don't see the point in keeping it open.

Thanks again! This package makes life a ton easier.

Side note while I've got you here, any tips on increasing the speed of reading in large datasets?

**Comment by sicarul** [comment]
@mdh1984 One important point to optimize loads is to make sure you are using the appropriate number of splits, if your cluster has 64 slices then it is a good idea to split your data into 64 files when uploading. Also make sure the S3 bucket you are using is colocated in the same region as the Redshift server.

https://docs.aws.amazon.com/redshift/latest/dg/t_splitting-data-files.html
https://docs.aws.amazon.com/redshift/latest/dg/r_STV_SLICES.html
