### ISSUE TITLE
Unable to specify subfolders of s3 bucket

### ISSUE THREAD

**Issue by raghuapce** [sicarul/redshiftTools#21]
I would like to upload data from R to redshift. The library doesn't have the functionality to point subfolders in S3 bucket. is there a solution for the same?

**Comment by sicarul** [comment]
Hey Rag, i haven't thought of this usecase before, can you explain to me why would you need to do that? Thanks!

**Comment by raghuapce** [comment]
Our data engineers are building pipelines which automates the transfer of data from each subfolders in s3  bucket to respective schema as tables in redshift. If we put all files in s3 bucket without subfolder, it may mess up the pipeline. Also, it would be difficult to trace if something goes wrong in pipeline.

**Comment by sicarul** [comment]
@raghuapce i partially understand, though this library uploads the data from the dataset with a random name, is this still what you want to do? We usually, for this library just have a dedicated S3 bucket which just has temporary data (which is deleted at the end of the process to avoid charges). It sounds like you also want the temporary data to be there for debugging?

**Comment by raghuapce** [comment]
@sicarul Our team has been allocated with only one s3 bucket and asked to create subfolders in the same for each project. So we don't have a dedicated s3 bucket. I did see temporary files are not deleted in s3 at the end of the process.  That's why I had asked a way to point subfolders in s3 bucket.

**Comment by sicarul** [comment]
That's weird, the process has a step for deleting the files. This would require changing some functions on internal.R and adding parameters on the external functions, you may send a PR with this or you can wait until i can do it. However, i recommend you to ask for a dedicated S3 bucket, it has no additional cost to have many buckets.

Thanks!

**Comment by raghuapce** [comment]
I have explored the function rs_create_table but I didn't find any parameter to delete temporary files in s3 bucket after creating the table in redshift. Also, could you explain, what are you referring to as PR?

**Comment by sicarul** [comment]
Sorry for the delay, rs_create_table calls rs_replace_table, which calls deletePrefix:
https://github.com/sicarul/redshiftTools/blob/8b7d2958885f5728840b95d66eb7a5148a7c1bcc/R/replace.R#L96

**Comment by sicarul** [comment]
@raghuapce can you tell me if you are still having problems with this? I've validated that the package always deletes it's temporary files. I'll close the issue for now.

**Comment by jtelleriar** [comment]
I also require access to a specific subfolder within a bucket :(
