### ISSUE TITLE
rs_upsert_table() connection timeout

### ISSUE THREAD

**Issue by ankhnesmerira** [sicarul/redshiftTools#27]
Hi there,
I've been using redshifttools package in R to write data back to redshift for months. Recently we've made some changes to redshift connections (which is outside of my control) and I get timeout error while running rs_upsert_table() function. The reason is that by the time the function is ready to write the data (only large data has this issue) back to redshift after copying the packets to S3 bucket, the connection has been timed-out and i get connection error. I've tried various combinations of dividing data to files because i still have the same issue, because i can't divide data to smaller sizes based on the key (otherwise new data will be over-written with latest chunk of data with the same key, if that makes any sense).

My question is, is there any way that the function could keep the connection alive while writing files to S3 bucket? so that by the time it's ready to load the data back to redshift from the bucket the connection hasn't been timed-out?

Many thanks.

**Comment by sicarul** [comment]
Hey @ankhnesmerira i don't understand why you can't divide in smaller chunks, the key should be unique so it wouldn't be an issue. If instead you need to add everything regardless of key, you should be appending, not upserting.
