### ISSUE TITLE
upsert with column list

### ISSUE THREAD

**Issue by ilyaminati** [sicarul/redshiftTools#30]
Amazon recommends [two different upsert methods](https://docs.aws.amazon.com/redshift/latest/dg/t_updating-inserting-using-staging-tables-.html). `redshiftTools` implements method 1, replacing existing rows. Could it also implement method 2, specifying a column list?

**Comment by ilyaminati** [comment]
@sicarul I have written an implementation of method 2 (specifying a column list) that I'd be happy to contribute. Right now, it's a separate function that i'm calling `rs_upsert_cols`. I could also combine it into a single function with `rs_upsert_table`, but it would modify the method signature. Please let me know if you're interested in either contribution.

**Comment by sicarul** [comment]
It sounds like a very special and different scenario, you are talking about this right?
```
Merge Method 2: Specifying a Column List
Use this method to update specific columns in the target table instead of overwriting entire rows. This method takes longer than the previous method because it requires an extra update step. Use this method if any of the following are true:

Not all of the columns in the target table are to be updated.

Most rows in the staging table will not be used in the updates.
```

If so, i'd say it would make more sense as a separate function. I'd not name it _cols, since all the functions with _table refer to operations on tables. What do you think of `rs_partial_upsert_table`?

**Comment by ilyaminati** [comment]
Yup, that scenario. I have an implementation I can contribute.

**Comment by ilyaminati** [comment]
I think to be transparent to the user, my suggestion is:
* Refer to the [Redshift upsert doc](https://docs.aws.amazon.com/redshift/latest/dg/t_updating-inserting-using-staging-tables-.html) in the redshiftTools doc
* Call the new function `rs_col_upsert_table`
* Create an alias to `rs_upsert_table` called `rs_row_upsert_table`

I'll send a pull request shortly.

**Comment by ilyaminati** [comment]
PR sent https://github.com/sicarul/redshiftTools/pull/31

**Comment by sicarul** [comment]
Thanks, i've sent you some comments, i'll close this issue and we can follow up in the PR, thanks for the contribution!
