### ISSUE TITLE
Missing connection parameter on README

### ISSUE THREAD

**Issue by mikejramsey56** [sicarul/redshiftTools#36]
A nit, but on your README page, under Drivers, RPostgres
test=dbGetQuery('select 1')

should be
test=dbGetQuery(**con**,'select 1')

Or at least on my windows RGui(64-bit) app.

**Comment by sicarul** [comment]
Thanks, i'll fix it on my next commit

**Comment by sicarul** [comment]
Done on dev branch, will merge soon
