### ISSUE TITLE
Recent Error

### ISSUE THREAD

**Issue by lexadavid** [sicarul/redshiftTools#4]
Hi,
I am getting lately this error when trying upload data.frame to Redshift.

[1] "Getting number of slices from Redshift"
[1] "4 slices detected, will split into 16 files"
Error in if (key == "") { : argument is of length zero

Do you know why it happens? It seems to be connected with uploadToS3 function

**Comment by sicarul** [comment]
Have you defined `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY`? It sounds like the error is coming from aws.s3, because that code isn't anywhere on redshiftTools `if (key == "") {`

**Comment by lexadavid** [comment]
yes I did defined keys.
But you were right it was problem with aws.s3. I installed older version from github (https://github.com/cloudyr/aws.s3/commit/ea777cbbc627dd864236ff278f3b617aa6322ade) and everything works again. Basically last 2 commits of aws.s3 cause problems for me. @sicarul

**Comment by sicarul** [comment]
Thanks for the information, i'll check if we need to change something to adapt for the new version

**Comment by sicarul** [comment]
It seems to work fine with the latest version of aws.s3, will close issue.
