### ISSUE TITLE
rs_create_table only uploads half of records in dataframe 

### ISSUE THREAD

**Issue by noahjgreen295** [sicarul/redshiftTools#41]
Hi,
Really grateful for this package! I'm running into some trouble with `rs_create_table`. No matter what I do, the function seems to upload exactly half of all the records in the data frame, rather than all of them. 

For example, if I create a data frame with 4 records and write to Redshift with `rs_create_table` like this:

```
df <- data.frame("val1" = 1:4, "val2" = 5:8)

conn <- dbConnect(RPostgres::Postgres(),
                  host = host,
                  port = port,
                  user = user,
                  password = password,
                  dbname = dbname,
                  sslmode='require')


table_name = "mts.vals"
rs_create_table(
  df, 
  dbcon=conn, 
  table_name=table_name,  
  bucket=s3_bucket,
  access_key = aws_access_key_id,
  secret_key = aws_secret_access_key,
  region = aws_default_region
)

```
I see this output in the console:
```

[1] "The provided data.frame has 4 rows"
[1] "Getting number of slices from Redshift"
[1] "3.16202013338398e-322 slices detected, will split into 3.16202013338398e-322 files"
[1] "Uploading ngreen/fepuobieukyyjelvgovpzrgvreappxwzxdoqmqjfgtvgvfwurq.0001"
[1] "Uploading ngreen/fepuobieukyyjelvgovpzrgvreappxwzxdoqmqjfgtvgvfwurq.0000"
[1] "Copying data from S3 into Redshift"
INFO:  Load into table 'ozlubiwvstkdcpjr' completed, 2 record(s) loaded successfully.
[1] "Deleting target table for replacement"
[1] "Insert new rows"
[1] "Drop staging table"
[1] "Committing changes"
[1] "Deleting temporary files from S3 bucket"
[1] "Deleting fepuobieukyyjelvgovpzrgvreappxwzxdoqmqjfgtvgvfwurq.0001"
[1] "Deleting fepuobieukyyjelvgovpzrgvreappxwzxdoqmqjfgtvgvfwurq.0000"
[1] TRUE

```

When I log into Redshift and run this:

`SELECT COUNT(1) FROM mts.vals `

I get an output of 2 rather than 4.

Any help appreciated - thanks!
-Noah

**Comment by noahjgreen295** [comment]
I have found that setting `split_files=1` will upload all records. However I have some very high record counts in my real data and would rather rely on redshiftTools to split files in S3.

**Comment by sicarul** [comment]
I'll try to replicate this bug during the week and debug, thanks for reporting!

**Comment by noahjgreen295** [comment]
Thanks for looking into this!

**Comment by sicarul** [comment]
@noahjgreen295 can you please check in an SQL client and report back, what do you get when running:

```select count(*) from stv_slices```

Thanks!!

**Comment by sicarul** [comment]
I did put some checks now just in case so you can also try with the new version reinstalling from github (devtools::install_github).
https://github.com/sicarul/redshiftTools/commit/ca55a9ce7b0de0dcee13e31b2fd3ee7f0d761a2f

**Comment by noahjgreen295** [comment]
I got `64` as the output of `select count(*) from stv_slices`.
Just tested the new version and it works - thanks!
