### ISSUE TITLE
load into table successfully, but reported error when deleting data in s3

### ISSUE THREAD

**Issue by jamesfeng1994** [sicarul/redshiftTools#45]
Hi Pablo,

I use "rs_create_table" to upload data into redshift. The uploading process is successful but there is error when deleting those temp files in s3:

INFO:  Load into table 'iytqadwbvpzmgsfj' completed, 1 record(s) loaded successfully.

Error in parse_aws_s3_response(r, Sig, verbose = verbose) : 
  Forbidden (HTTP 403).

**Comment by sicarul** [comment]
Maybe your user has only permission to upload but not delete the data? Can you check with another AWS tool with the same AWS Access key?

**Comment by sicarul** [comment]
I'll close this issue, let me know if anything else
