### ISSUE TITLE
Error with curl?

### ISSUE THREAD

**Issue by JakeRuss** [sicarul/redshiftTools#46]
Hey Pablo,

I've recently discovered this package and I have been using it with great success. So thank you! 

I've encountered an error message that does not have an existing issue, so I wanted to report it, but I'm not quite sure what the problem is, so I can't give a reproducible example. As you'll see I am trying to load a very large data frame. So maybe that is the issue. 

```
The provided data.frame has 15516052 rows and 546 columns
Getting number of slices from Redshift
1.97626258336499e-323 slices detected, will split into 4816 files
Uploading 4816 files with prefix bmwgevwtjusrfqoeajpdvqbklsmtlhfevocadmkthdtotijroy to bucket my-bucket-name
Uploading file 575/4816 [=============>--------------------------------------------------------------------------------------------------------]
Error in curl::curl_fetch_memory(url, handle = handle) : 
  OpenSSL SSL_write: SSL_ERROR_ZERO_RETURN, errno 32
```

Also, sometimes I get,

```
Error in curl::curl_fetch_memory(x$url$url, handle = x$url$handle) :
Error in the HTTP2 framing layer
```
Do you understand either of these error messages?

**Comment by sicarul** [comment]
I'd suggest you upload your data frame in pieces to reduce the possibility of this error happening. Also i'd use some scheduler which has retries like airflow, the error you see is just random HTTPS failures happening while sending the data to Amazon S3, not much we can do from the package side about that i think

**Comment by JakeRuss** [comment]
@sicarul Thanks for the suggestion. I had this idea myself yesterday and it worked, I just looped through the segments of the dataset in stages. I'll close.
