### ISSUE TITLE
pb_tick

### ISSUE THREAD

**Issue by ghost** [sicarul/redshiftTools#51]
Hi, looks like I have a bug with pb_tick (progress bar function I think). Any idea how to resolve it? I am new at R so I am not even sure which library this function comes from.

Here is my error message and traceback. Any help is greatly appreciated!

Error in pb_tick(self, private, len, tokens) : !self$finished is not TRUE

> traceback()
8: stop(simpleError(msg, call = if (p <- sys.parent(1L)) sys.call(p)))
7: stopifnot(!self$finished)
6: pb_tick(self, private, len, tokens)
5: pb$tick()
4: .f(.x[[i]], .y[[i]], ...)
3: map2(splitted, 1:split_files, upload_part)
2: uploadToS3(df, bucket, split_files, access_key, secret_key, session_token, 
       region)
1: rs_replace_table(test, dbcon = con_dw, table_name = "sometablename", 
       bucket = "mybucket", access_key = "myaccesskey", 
       secret_key = "mysecretkey")

**Comment by dzheng-root** [comment]
https://github.com/r-lib/revdepcheck/pull/100/commits/c68efe393ec370149f3b72c98f1cb6fe202d92db

I tried to reinstall this package but says it is not available for R version 3.6.1. Not sure what other package has pb_tick in it...

**Comment by ghost** [comment]
Nevermind, I avoided it by defining split_files = 1 I think.
