### ISSUE TITLE
Error message

### ISSUE THREAD

**Issue by ylteq** [sicarul/redshiftTools#6]
Hi, i am very excited about this tool.
But I got this message using "rs_upsert_table", i have everything specified and set up including bucket,split_files,region ,access_key ,secret_key,iam_role_arn. Thank you for your time and help!

**Error in curl_fetch_memory(uri) : Timeout was reached
Error in curl_fetch_memory(uri) : 
  URL using bad/illegal format or missing URL
Error in role[["AWS_ACCESS_KEY_ID"]] : subscript out of bounds****

**Comment by sicarul** [comment]
@ylteq i just saw this, are you sure the parameters are correct? Sounds like some of the environment variables may be wrong

**Comment by sicarul** [comment]
Closing for now, let me know if you need further help
