### ISSUE TITLE
Error in if (nrow(data) == 0) { : missing value where TRUE/FALSE needed

### ISSUE THREAD

**Issue by DemianTinkiel** [sicarul/redshiftTools#7]
with  AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY specified via Sys.setenv

redshiftTools 0.11
aws.s3 0.3.3

encountered when trying to rs_replace_table

--------Platform info ----
version
               _                           
platform       x86_64-redhat-linux-gnu     
arch           x86_64                      
os             linux-gnu                   
system         x86_64, linux-gnu           
status                                     
major          3                           
minor          4.0                         
year           2017                        
month          04                          
day            21                          
svn rev        72570                       
language       R                           
version.string R version 3.4.0 (2017-04-21)
nickname       You Stupid Darkness

**Comment by DemianTinkiel** [comment]
> traceback()
2: uploadToS3(data, bucket, split_files)
1: rs_replace_table(mytableValues, dbcon = con, tableName = "mytable", 
       bucket = "mybucket")

**Comment by sicarul** [comment]
nrow(data) == 0 is throwing NA, are you sure you have a data.frame object as the first parameter to rs_replace_table instead of some other type @DemianTinkiel ?

You can check with class(mytableValues)

**Comment by DemianTinkiel** [comment]
Hey, apologies for the delay. I found the issue, I was using the wrong dbCon object, as it was created using another library. Sorry!

**Comment by sicarul** [comment]
Cool!
