### ISSUE TITLE
adding 'headers =' to 'put_object'

### ISSUE THREAD

**Issue by bmbagley** [sicarul/redshiftTools#8]
I have been getting an Access Denied error when trying to use the `rs_replace_table` command because I am unable to specify a list of headers for amz server side encryption.  Can this get added to both commands?

```
rs_replace_table(data = temp, dbcon = con, tablename = 'table.name',
    bucket = 'bucket_location',
    headers = list('x-amz-server-side-encryption' = 'xx'))
```

When calling `aws.s3::put_object` by itself, this works with our connection but I am unable to figure out how to add this into the call.

**Comment by sicarul** [comment]
@bmbagley Can you send this as a pull request?

**Comment by sicarul** [comment]
I'll close this for now, let me know if you want to add it
